export const tabledata = [
  {
    eventname: "song1",
    date: "25-1-2025",
    time: "10: 30",
    venue: "tvm",
    iscompleted: "yes",
  },
  {
    eventname: "song1",
    date: "25-1-2025",
    time: "10: 30",
    venue: "tvm",
    iscompleted: "yes",
  },
  {
    eventname: "song1",
    date: "25-1-2025",
    time: "10: 30",
    venue: "tvm",
    iscompleted: "yes",
  },
  {
    eventname: "song1",
    date: "25-1-2025",
    time: "10: 30",
    venue: "tvm",
    iscompleted: "yes",
  },
  {
    eventname: "song1",
    date: "25-1-2025",
    time: "10: 30",
    venue: "tvm",
    iscompleted: "yes",
  },
  {
    eventname: "song1",
    date: "25-1-2025",
    time: "10: 30",
    venue: "tvm",
    iscompleted: "yes",
  },
  {
    eventname: "song1",
    date: "25-1-2025",
    time: "10: 30",
    venue: "tvm",
    iscompleted: "yes",
  },
];
